import Link from "next/link";
import { BrandMark } from "@/components/brand-mark";

export const dynamic = "force-static";

export const metadata = {
  title: "Terms & Conditions — Thinking Outside the Box",
  description:
    "Plain-language terms for using this anonymous public-chat platform.",
};

const LAST_UPDATED = "2026-05-21";

export default function TermsPage() {
  return (
    <div className="mx-auto flex w-full max-w-3xl flex-1 flex-col px-4 pt-6 pb-8">
      <header className="mb-6 flex flex-wrap items-start justify-between gap-3 border-b border-[var(--border)] pb-3">
        <div className="flex min-w-0 items-center gap-2">
          <BrandMark size={40} />
          <div className="min-w-0">
            <h1 className="text-lg font-semibold tracking-tight">
              Terms &amp; Conditions
            </h1>
            <p className="text-xs text-[var(--muted)]">
              Last updated {LAST_UPDATED}
            </p>
          </div>
        </div>
        <Link
          href="/"
          className="shrink-0 rounded-md border border-[var(--border)] px-3 py-1.5 text-xs hover:bg-black/3 dark:hover:bg-white/5"
        >
          ← Home
        </Link>
      </header>

      <Section title="What this is">
        <p>
          <strong>Thinking Outside the Box</strong> is a free, open-source
          platform for chatting with an AI in public. You get an
          anonymous handle on first visit, you can mark any chat as Public or
          Unlisted, and the site surfaces other people who are exploring
          similar topics in real time.
        </p>
        <p>
          By using the site you agree to these terms. If you don&apos;t agree,
          please don&apos;t use it.
        </p>
      </Section>

      <Section title="Anonymous identity, your responsibility">
        <p>
          Your identity is a random handle stored in a cookie on this device.
          Anyone who has access to your device can post under your handle. You
          are responsible for everything posted under your handle from any
          device you control.
        </p>
        <p>
          We do not authenticate you. We cannot recover a lost handle, transfer
          a handle between devices, or prove ownership of a handle to a third
          party.
        </p>
      </Section>

      <Section title="Acceptable use">
        <p>You agree not to use the site to:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>
            Post content that is illegal where you live or where the service is
            hosted — including, without limitation, CSAM, credible threats of
            violence, doxxing, or content that infringes intellectual property
            rights.
          </li>
          <li>
            Harass, stalk, intimidate, or impersonate any person or
            organisation.
          </li>
          <li>
            Attempt to deanonymise, profile, or aggregate-track other users.
          </li>
          <li>
            Probe, scan, or test the vulnerability of the platform without the
            written consent of the maintainer; or breach any security or
            authentication measures. Good-faith security research is welcome
            via the disclosure process in{" "}
            <a
              href="https://github.com/qwertykeypadapple/thinking-outside-the-box/blob/main/SECURITY.md"
              target="_blank"
              rel="noopener noreferrer"
              className="text-[var(--accent)] hover:underline"
            >
              SECURITY.md
            </a>
            .
          </li>
          <li>
            Use automated systems to scrape, mirror, flood, or otherwise place
            disproportionate load on the platform.
          </li>
          <li>
            Attempt to manipulate the assistant via prompt injection in order
            to exfiltrate other users&apos; data or alter platform state.
          </li>
        </ul>
      </Section>

      <Section title="Public chats are public">
        <p>
          When you mark a chat as <strong>Public</strong>, it appears in the
          public feed and is reachable by anyone on the internet, indefinitely.
          Search engines may index it. Other users may quote it. We attempt to
          redact structured personal information automatically, but{" "}
          <strong>nothing you write in a public chat should be treated as
          private</strong>. Do not put confidential, sensitive, or
          identity-revealing information into a chat you intend to make public.
        </p>
      </Section>

      <Section title="AI outputs">
        <p>
          The replies you see are generated by a large language model. They
          can be incomplete, biased, or simply wrong. <strong>
            Nothing the assistant says is professional advice
          </strong>{" "}
          — not medical, legal, financial, mental-health, safety, or otherwise.
          Use independent judgement and consult a qualified professional for
          anything that matters.
        </p>
        <p>
          The model can also generate content that you, we, or others may find
          objectionable. We apply automated moderation but it is imperfect.
          Report anything that violates these terms via the in-app report
          button.
        </p>
      </Section>

      <Section title="Your content">
        <p>
          You retain whatever rights you have in the messages you write. By
          posting them on this platform, you grant the maintainer a worldwide,
          royalty-free, non-exclusive licence to store, display, transmit, and
          process those messages for the purpose of operating the service —
          including making public chats visible to other users, generating
          topic embeddings, and surfacing matches.
        </p>
        <p>
          This licence ends for a given chat when you delete it, except where
          we are required by law to retain a copy or where a copy has already
          been cached or quoted by a third party outside our control.
        </p>
      </Section>

      <Section title="Moderation and removal">
        <p>
          We may, at our sole discretion, hide, redact, or remove any content
          that violates these terms or otherwise risks the health of the
          platform. We may also restrict or revoke a handle&apos;s ability to
          post if it engages in abuse, spam, or attempted exploitation.
        </p>
        <p>
          We do not pre-screen content. Automated classification runs on every
          public message and may auto-hide content of high concern; human
          review of the report queue is best-effort.
        </p>
      </Section>

      <Section title="Open source">
        <p>
          The platform is open source under the MIT licence. You can read the
          code, fork it, or self-host your own instance. See the{" "}
          <a
            href="https://github.com/qwertykeypadapple/thinking-outside-the-box"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[var(--accent)] hover:underline"
          >
            GitHub repository
          </a>
          .
        </p>
      </Section>

      <Section title="No warranty">
        <p>
          The service is provided on an <strong>&quot;as is&quot; and &quot;as
          available&quot;</strong> basis. To the maximum extent permitted by
          law, the maintainer disclaims all warranties, express or implied,
          including merchantability, fitness for a particular purpose, and
          non-infringement. We do not warrant that the service will be
          uninterrupted, error-free, or secure, or that AI outputs will be
          accurate or appropriate.
        </p>
      </Section>

      <Section title="Limitation of liability">
        <p>
          To the maximum extent permitted by law, the maintainer is not liable
          for any indirect, incidental, special, consequential, or punitive
          damages, or for any loss of profits, data, goodwill, or other
          intangible losses, arising from your use of or inability to use the
          service. Where liability cannot be excluded, it is limited to the
          greater of (a) the amount you have paid to the maintainer for the
          service in the twelve months preceding the claim (which, for the
          free tier that everyone uses, is zero) or (b) USD 50.
        </p>
      </Section>

      <Section title="Donations are not payments for service">
        <p>
          Optional donations via GitHub Sponsors or Open Collective support
          ongoing development. They do not purchase any specific feature,
          uptime guarantee, or commercial-grade SLA. Donor perks are listed on
          the <Link href="/sponsors" className="text-[var(--accent)] hover:underline">sponsors page</Link>.
        </p>
      </Section>

      <Section title="Changes to the service or these terms">
        <p>
          The platform is under active development. Features may change, be
          added, or be removed. We may update these terms; the{" "}
          <em>Last updated</em> date at the top reflects the current version.
          Material changes will be surfaced in-product where reasonably
          possible. Continued use after a change constitutes acceptance.
        </p>
      </Section>

      <Section title="Termination">
        <p>
          You may stop using the service at any time. You can delete every
          piece of data tied to your handle from your profile page. We may
          suspend or terminate access for any handle that violates these terms.
        </p>
      </Section>

      <Section title="Governing law">
        <p>
          These terms are governed by the laws of the maintainer&apos;s primary
          place of residence. Disputes will be handled there unless a mandatory
          consumer-protection law of your residence specifies otherwise.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          For questions about these terms, open an issue on the{" "}
          <a
            href="https://github.com/qwertykeypadapple/thinking-outside-the-box/issues"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[var(--accent)] hover:underline"
          >
            GitHub repo
          </a>
          .
        </p>
      </Section>

      <footer className="mt-6 border-t border-[var(--border)] pt-4 text-xs text-[var(--muted)]">
        <Link href="/privacy" className="hover:text-[var(--foreground)]">
          Privacy Policy
        </Link>
        <span className="mx-2">·</span>
        <Link href="/" className="hover:text-[var(--foreground)]">
          Home
        </Link>
      </footer>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-6">
      <h2 className="mb-2 text-sm font-semibold tracking-tight">{title}</h2>
      <div className="space-y-2 text-sm text-[var(--muted)] leading-relaxed">
        {children}
      </div>
    </section>
  );
}
